apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jtiu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jtiu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jtiu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jtiu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jtiu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uahk-tenant/rhtap-demo-app/hacbs-test-project-jtiu@sha256:c4d5e7404e384f9735ea036c8e149ce044dc9bee48e8616663f94872c98ea631
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
